osx_image: xcode9
language: objective-c
cache:
  - bundler
  - cocoapods
branchers:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem install bundler
  - bundle install
script: bundle exec fastlane funky
