lane :funky do
  scan(
    code_coverage: true,
    open_report: false,
  )
  if git_branch() == "develop"
    print "OK Dev"
    funky_deploy
  elsif git_branch() == "master"
    funky_deploy
  end
end

lane :funky_deploy do
  pod_lib_lint
  pod_push
  print "[!!] Deploy\n"
end
